web:
  build: .
  command: python /code/nppes_fhir_demo/serve_nppes.py
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - esdb
esdb:
  image: elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"
